"use strict";
const TX_TYPES =  {
    GENESIS_TRANSACTION: 1,
    PAYMENT_TRANSACTION: 2,

    REGISTER_NAME_TRANSACTION: 3,
    UPDATE_NAME_TRANSACTION: 4,
    SELL_NAME_TRANSACTION: 5,
    CANCEL_SELL_NAME_TRANSACTION: 6,
    BUY_NAME_TRANSACTION: 7,

    CREATE_POLL_TRANSACTION: 8,
    VOTE_ON_POLL_TRANSACTION: 9,

    ARBITRARY_TRANSACTION: 10,

    ISSUE_ASSET_TRANSACTION: 11,
    TRANSFER_ASSET_TRANSACTION: 12,
    CREATE_ORDER_TRANSACTION: 13,
    CANCEL_ORDER_TRANSACTION: 14,
    MULTI_PAYMENT_TRANSACTION: 15,

    DEPLOY_AT_TRANSACTION: 16,

    MESSAGE_TRANSACTION: 17
};

const QORA_DECIMALS = 100000000

const PROXY_URL = "/proxy/" // Proxy for api calls

export { TX_TYPES as default, QORA_DECIMALS, PROXY_URL }